# Generated by Django 2.2.5 on 2020-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201015_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.IntegerField(default=0),
        ),
    ]
