# Generated by Django 2.2.5 on 2020-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(),
        ),
    ]
